---
title: "Class Notes glm"
author: "Holly Westbrook"
date: "3/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
source("build_collapse_table.r") #loading up the data frames from the last class, bc erin stored it into an r script for easy access

glimpse(timeseries)

any(FALSE,FALSE) #are there any trues in this data?
any(FALSE,FALSE,TRUE)

model_data = collapse  %>% 
  group_by(stockid, stocklong, region) %>% 
  summarise(ever_collapsed = any (ever_collapsed))#did our stock ever collapse, also summarize will drop any variables that you don't create in summarize or dont group by

glimpse(model_data)
summary(model_data)

model_l = glm(ever_collapsed ~region, data=model_data, family = "binomial") #going to transfer the y variable to fit into a binomial distribution, lm would have it fit to a gaussian distribution
summary(model_l)

model_data = collapse  %>% 
  group_by(stockid, stocklong, region) %>% 
  summarise(ever_collapsed = any (ever_collapsed)) %>% 
  ungroup()

model_data %>% distinct(region) %>%  arrange(region) #tried to do this, didn't work, did it in base r instead
sort(unique(model_data$region))

summary(model_l) #the estimates are all relative to the first variable provided, which is the atlantic ocean in this case

#generate prediction plot
regions = model_data %>%  distinct(region)
regions

model_l_predict = predict(model_l,  newdata = regions, se.fit = TRUE, type = "response") #we want our preditions to be 0 to 1

head(model_l_predict)

collapse_region_predictions = cbind(regions, model_l_predict)
head(collapse_region_predictions)

#plot it
ggplot(data = collapse_region_predictions, aes(x = region, y = fit, fill = region))+
  geom_bar(stat="identity", show.legend = FALSE)+ #means actually make the length y instead of trying to make a histogram
  geom_errorbar(aes(ymin = fit-se.fit, ymax = fit+se.fit))+
  coord_flip()+ #gives room for the axes names 
  xlab("Probability of Experiencing Collapse")+
  ylab("Region")


#Poisson model
glimpse(timeseries_values_views)
head(timeseries_values_views)
#MSY = maximum sustainable yeild
#B biomas

u_summary = timeseries_values_views %>% 
  left_join(stock, by=c("stockid", "stocklong")) %>% 
  filter(!is.na(BdivBmsypref),
         !is.na(UdivUmsypref)) %>% 
  group_by(stockid, stocklong, region) %>% 
  summarise(yrs_data = n(), 
            ratio_yrs_overfished = sum(UdivUmsypref >1)/yrs_data,
            ratio_yrs_low_stock = sum(BdivBmsypref <1)/yrs_data) %>% 
  select(-yrs_data) #getting rid fo tis variable bc we wanna use it later

collapse_summary = collapse %>% 
  group_by(stockid, stocklong,region) %>% 
  summarise(yrs_data = n(), 
            yrs_collapsed = sum(current_collapse)/yrs_data)

head(collapse_summary)

#let's join it with our other data
collapse_summary = collapse %>% 
  group_by(stockid, stocklong,region) %>% 
  summarise(yrs_data = n(), 
            yrs_collapsed = sum(current_collapse)) %>% 
  inner_join(u_summary, by=c("stockid", "stocklong", "region")) #innerjoin will dump any data that we don't have all the variables for 

glimpse(collapse_summary)

table(collapse_summary$yrs_collapsed) #wow lots of zeros

collapse_summary_zero_trunc = collapse_summary %>% 
  filter(yrs_collapsed != 0)
head(collapse_summary_zero_trunc)

model_p = glm(yrs_collapsed ~ ratio_yrs_overfished + ratio_yrs_low_stock + 
                offset(log(yrs_data)), family = "poisson", data = collapse_summary_zero_trunc)
summary(model_p)

library(AER)
AER::dispersiontest(model_p)
#model is overdispersed

model_qp = glm(yrs_collapsed ~ ratio_yrs_overfished + ratio_yrs_low_stock + 
                offset(log(yrs_data)), family = "quasipoisson", data = collapse_summary_zero_trunc)
summary(model_qp)

```